// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aptkoloubipyijnjqihe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwdGtvbG91YmlweWlqbmpxaWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTU4NTYsImV4cCI6MjA3NDIzMTg1Nn0.00DOPQSHtpl0ZPonEvYiR8lY9DrBQ_4MJoges1FXl90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});